"""empty message

Revision ID: 80175bfadef7
Revises: 45d0aa472f92
Create Date: 2020-04-16 12:23:50.874412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80175bfadef7'
down_revision = '45d0aa472f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VenueGenres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('VenueGenres')
    # ### end Alembic commands ###
