"""empty message

Revision ID: d7a25cb0a569
Revises: 18200c000334
Create Date: 2020-04-14 19:43:50.017026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a25cb0a569'
down_revision = '18200c000334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArtistGenres')
    op.add_column('Artist', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.create_table('ArtistGenres',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='ArtistGenres_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='ArtistGenres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id', name='ArtistGenres_pkey')
    )
    # ### end Alembic commands ###
